# -*- coding: utf-8 -*-
"""dfdc_data_zips_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzPVSHCPGV1chw96G5lVgAoMYupYtKNo
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install insightface mediapipe timm transformers librosa av

import os, json, csv, zipfile, shutil, traceback
import torch
import numpy as np
import cv2
import librosa
from tqdm import tqdm

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

ZIP_DIR = "/content/drive/MyDrive/DFDC_zips"
OUT_DIR = "/content/drive/MyDrive/DFDC_processed"
TMP_DIR = "/content/dfdc_tmp"

ZIP_PROGRESS = "/content/drive/MyDrive/dfdc_zip_progress.csv"
VIDEO_PROGRESS = "/content/drive/MyDrive/dfdc_video_progress.json"

os.makedirs(TMP_DIR, exist_ok=True)
for c in ["real", "fake"]:
    os.makedirs(os.path.join(OUT_DIR, c), exist_ok=True)

def load_zip_done():
    done = set()
    if os.path.exists(ZIP_PROGRESS):
        with open(ZIP_PROGRESS) as f:
            for r in csv.reader(f):
                done.add(r[0])
    return done

def mark_zip_done(z):
    with open(ZIP_PROGRESS, "a") as f:
        csv.writer(f).writerow([z])

def load_video_done():
    if os.path.exists(VIDEO_PROGRESS):
        with open(VIDEO_PROGRESS) as f:
            return json.load(f)
    return {}

def mark_video_done(d):
    with open(VIDEO_PROGRESS, "w") as f:
        json.dump(d, f)

!pip install -U onnxruntime

from insightface.app import FaceAnalysis
import timm
from transformers import Wav2Vec2Processor, Wav2Vec2Model
import mediapipe as mp

!pip install mediapipe==0.10.9

import mediapipe as mp

face_app = FaceAnalysis(name="buffalo_l")
face_app.prepare(ctx_id=0)

spatial_model = timm.create_model("efficientnet_b4", pretrained=True, num_classes=0).to(DEVICE).eval()

wav_proc = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base-960h")
wav_model = Wav2Vec2Model.from_pretrained("facebook/wav2vec2-base-960h").to(DEVICE).eval()

# mp_face = mp.solutions.face_mesh.FaceMesh(static_image_mode=False)

def read_frames(video, max_frames=32):
    cap = cv2.VideoCapture(video)
    frames = []
    while len(frames) < max_frames and cap.isOpened():
        ok, f = cap.read()
        if not ok: break
        frames.append(cv2.cvtColor(f, cv2.COLOR_BGR2RGB))
    cap.release()
    return frames

@torch.no_grad()
def extract_spatial_faces(frames, min_face=40):
    """
    frames: list of HWC uint8 frames
    returns: torch.Tensor [N, C] or None
    """
    embeddings = []

    for frame in frames:
        faces = face_app.get(frame)

        if not faces:
            continue

        face = faces[0]

        # --- SAFE bbox handling ---
        if face.bbox is None:
            continue

        x1, y1, x2, y2 = map(int, face.bbox)

        # skip tiny or invalid boxes
        if x2 <= x1 or y2 <= y1:
            continue
        if (x2 - x1) < min_face or (y2 - y1) < min_face:
            continue

        h, w, _ = frame.shape
        x1, y1 = max(0, x1), max(0, y1)
        x2, y2 = min(w, x2), min(h, y2)

        crop = frame[y1:y2, x1:x2]

        if crop.size == 0:
            continue

        # preprocess for EfficientNet
        crop = cv2.resize(crop, (224, 224))
        crop = torch.from_numpy(crop).permute(2, 0, 1).float() / 255.0
        crop = crop.unsqueeze(0).to(DEVICE)

        feat = spatial_model(crop)  # EfficientNet / Swin
        embeddings.append(feat.squeeze(0).cpu())

    if not embeddings:
        return None

    return torch.stack(embeddings)

def extract_motion(frames):
    feats = []
    prev = None
    for f in frames:
        g = cv2.cvtColor(f, cv2.COLOR_RGB2GRAY)
        if prev is None:
            feats.append(torch.zeros(256))
        else:
            diff = cv2.absdiff(prev, g)
            feats.append(torch.tensor(diff.mean()).repeat(256))
        prev = g
    return torch.stack(feats)

@torch.no_grad()
def extract_audio(video):
    y, sr = librosa.load(video, sr=16000)
    inp = wav_proc(y, return_tensors="pt", sampling_rate=16000).input_values.to(DEVICE)
    emb = wav_model(inp).last_hidden_state.mean(dim=1)
    return emb.repeat(32,1).cpu()

import numpy as np

# 68-landmark indices (standard)
LEFT_EYE = [36, 37, 38, 39, 40, 41]
RIGHT_EYE = [42, 43, 44, 45, 46, 47]

def eye_aspect_ratio(lm, idx):
    p = lm[idx]
    vertical = np.linalg.norm(p[1] - p[5]) + np.linalg.norm(p[2] - p[4])
    horizontal = np.linalg.norm(p[0] - p[3])
    return vertical / (2.0 * horizontal + 1e-6)

def extract_rppg_signal(frames):
    means = []
    for f in frames:
        roi = f[f.shape[0]//4:3*f.shape[0]//4,
                f.shape[1]//4:3*f.shape[1]//4]
        r, g, b = roi[:,:,0].mean(), roi[:,:,1].mean(), roi[:,:,2].mean()
        means.append([r, g, b])

    means = np.array(means)
    means = (means - means.mean(0)) / (means.std(0) + 1e-6)

    X = means[:,0] - means[:,1]
    Y = means[:,0] + means[:,1] - 2*means[:,2]
    return X - Y

def extract_physiology(frames):
    physiology = []

    rppg = extract_rppg_signal(frames)
    prev = rppg[0]

    for i, f in enumerate(frames):
        faces = face_app.get(f)

        ear = 0.0
        blink = 0.0

        if faces:
            lm = faces[0].landmark_2d_68
            left = eye_aspect_ratio(lm, LEFT_EYE)
            right = eye_aspect_ratio(lm, RIGHT_EYE)
            ear = (left + right) / 2.0
            blink = 1.0 if ear < 0.2 else 0.0

        delta = rppg[i] - prev
        prev = rppg[i]

        physiology.append([
            rppg[i],     # pulse signal
            delta,       # temporal change
            ear,         # eye openness
            blink        # blink state
        ])

    return torch.tensor(physiology, dtype=torch.float32)

def process_video(video_path, info, zip_name, video_done):
    vid = os.path.splitext(os.path.basename(video_path))[0]
    label = "fake" if info["label"] == "FAKE" else "real"

    if vid in video_done:
        return

    out_dir = os.path.join(OUT_DIR, label, vid)
    os.makedirs(out_dir, exist_ok=True)

    try:
        frames = read_frames(video_path)
        if len(frames) < 5:
            return

        features = {
            "spatial": extract_spatial_faces(frames),
            "motion": extract_motion(frames),
            "audio": extract_audio(video_path),
            "physiology": extract_physiology(frames),
            "mask": torch.ones(len(frames))
        }

        torch.save(features, f"{out_dir}/features.pt")

        meta = {
            "label": info["label"],
            "original": info.get("original"),
            "zip": zip_name
        }

        with open(f"{out_dir}/meta.json", "w") as f:
            json.dump(meta, f, indent=2)

        video_done[vid] = True

    except Exception:
        print("⚠️ Video failed:", vid)
        traceback.print_exc()

def process_zip(zip_name, video_done):
    zip_path = os.path.join(ZIP_DIR, zip_name)

    with zipfile.ZipFile(zip_path) as z:
        z.extractall(TMP_DIR)

    part = os.path.join(TMP_DIR, os.listdir(TMP_DIR)[0])

    with open(os.path.join(part, "metadata.json")) as f:
        meta = json.load(f)

    # load or initialize in-memory video_done dict
    video_done = load_video_done()  # returns dict
    total_videos = len(meta)
    processed = 0
    last_write = time.time()

    for idx, (v, info) in enumerate(meta.items(), start=1):
        vid = os.path.splitext(v)[0]

        # skip if already processed
        if vid in video_done and video_done[vid].get("status") == "DONE":
            processed += 1
            if idx % 50 == 0:
                log(f"{zip_name}: already processed {idx}/{total_videos}")
            continue

        try:
            process_video(os.path.join(part, v), info, zip_name, video_done)
            video_done[vid] = {"status": "DONE", "zip": zip_name}
            log(f"{zip_name} | {vid} DONE ({idx}/{total_videos})")
        except Exception as e:
            # capture traceback text
            tb = traceback.format_exc()
            video_done[vid] = {"status": "FAILED", "error": str(e)}
            log(f"{zip_name} | {vid} FAILED ({idx}/{total_videos}) - {e}")
            # write detailed traceback to separate file
            with open(os.path.join(OUT_DIR, "errors", f"{zip_name}_{vid}.log"), "w") as ef:
                ef.write(tb)

        processed += 1

        # every 50 videos or every 60s, flush progress to disk
        if (idx % 50 == 0) or (time.time() - last_write > 60):
            # write JSON progress atomically
            tmp_json = VIDEO_PROGRESS + ".tmp"
            with open(tmp_json, "w") as jf:
                json.dump(video_done, jf)
            os.replace(tmp_json, VIDEO_PROGRESS)
            last_write = time.time()
            log(f"{zip_name}: progress flushed at {idx}/{total_videos}")

    # after finishing zip, mark zip done in CSV atomically
    tmp_csv = ZIP_PROGRESS + ".tmp"
    # append row
    with open(tmp_csv, "w", newline="") as f:
        writer = csv.writer(f)
        # copy existing header and rows (if any)
        if os.path.exists(ZIP_PROGRESS):
            with open(ZIP_PROGRESS, "r") as oldf:
                old = oldf.read()
        else:
            old = ""
        f.write(old)
        writer.writerow([zip_name, "DONE"])
    os.replace(tmp_csv, ZIP_PROGRESS)

zip_done = load_zip_done()
video_done = load_video_done()

for zip_name in sorted(os.listdir(ZIP_DIR)):
    if not zip_name.endswith(".zip"): continue
    if zip_name in zip_done: continue

    process_zip(zip_name, video_done)
    mark_zip_done(zip_name)
    print("✅ ZIP DONE:", zip_name)

class DFDCFeatureDataset(torch.utils.data.Dataset):
    def __init__(self, root):
        self.items = []
        for lbl in ["real", "fake"]:
            base = os.path.join(root, lbl)
            for vid in os.listdir(base):
                self.items.append((os.path.join(base, vid), 0 if lbl=="real" else 1))

    def __getitem__(self, i):
        path, y = self.items[i]
        feats = torch.load(os.path.join(path, "features.pt"))
        return feats, torch.tensor(y)

    def __len__(self):
        return len(self.items)

"""# **New method**"""

!pip install -q insightface==0.7.3 mediapipe timm transformers librosa av soundfile
!pip install -q -U onnxruntime

# Robust DFDC preprocessing for Colab
# - Streams videos from zip (extracts single video at a time)
# - Atomic progress writes, resumable
# - Uses ffmpeg to extract audio to wav
# - Safe ctx_id selection for insightface
# - Removes temp files immediately after processing
# - Better logging & error reporting

# Install dependencies (run once)


import os, json, csv, zipfile, shutil, traceback, time, subprocess, sys
from pathlib import Path
from tqdm import tqdm
import torch
import numpy as np
import cv2
import librosa
import soundfile as sf

# ---------- CONFIG ----------
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
CTX_ID = 0 if torch.cuda.is_available() else -1    # insightface ctx: 0 for GPU, -1 for CPU
ZIP_DIR = "/content/drive/MyDrive/DFDC_zips"
OUT_DIR = "/content/drive/MyDrive/DFDC_processed"
TMP_DIR = "/content/dfdc_tmp"            # base temp dir
ZIP_PROGRESS = "/content/drive/MyDrive/dfdc_zip_progress.csv"
VIDEO_PROGRESS = "/content/drive/MyDrive/dfdc_video_progress.json"
ERRORS_DIR = os.path.join(OUT_DIR, "errors")
MAX_FRAMES = 32      # frames sampled per video
MIN_FACE = 40        # min face box size to accept
AUDIO_SR = 16000     # sampling rate for audio
# -----------------------------



os.makedirs(TMP_DIR, exist_ok=True)
os.makedirs(OUT_DIR, exist_ok=True)
os.makedirs(ERRORS_DIR, exist_ok=True)
for c in ["real", "fake"]:
    os.makedirs(os.path.join(OUT_DIR, c), exist_ok=True)

def ensure_dir(path):
    os.makedirs(path, exist_ok=True)

def log(*args, **kwargs):
    ts = time.strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}]", *args, **kwargs)
    sys.stdout.flush()

# Progress helpers (atomic writes)
def load_zip_done():
    done = set()
    if os.path.exists(ZIP_PROGRESS):
        try:
            with open(ZIP_PROGRESS, newline='') as f:
                for r in csv.reader(f):
                    if r: done.add(r[0])
        except Exception:
            log("Warning: failed to read zip progress CSV, will start fresh.")
    return done

def mark_zip_done(z):
    # append row atomically
    tmp = ZIP_PROGRESS + ".tmp"
    with open(tmp, "a", newline='') as f:
        csv.writer(f).writerow([z, "DONE", time.time()])
    # if original exists, append; else replace
    if os.path.exists(ZIP_PROGRESS):
        with open(ZIP_PROGRESS, "ab") as out, open(tmp, "rb") as inp:
            out.write(inp.read())
        os.remove(tmp)
    else:
        os.replace(tmp, ZIP_PROGRESS)

def load_video_done():
    if os.path.exists(VIDEO_PROGRESS):
        with open(VIDEO_PROGRESS) as f:
            try:
                return json.load(f)
            except Exception:
                log("WARNING: corrupted video progress file; starting with empty progress.")
                return {}
    return {}

def save_video_done(video_done):
    tmp = VIDEO_PROGRESS + ".tmp"
    with open(tmp, "w") as f:
        json.dump(video_done, f)
    os.replace(tmp, VIDEO_PROGRESS)

# ---------- Models (create once) ----------
from insightface.app import FaceAnalysis
import timm
from transformers import Wav2Vec2Processor, Wav2Vec2Model

log("Initializing models (this may take a while)...")
face_app = FaceAnalysis(name="buffalo_l")
face_app.prepare(ctx_id=CTX_ID, det_size=(640, 640))

spatial_model = timm.create_model("efficientnet_b4", pretrained=True, num_classes=0)
spatial_model.eval()
if DEVICE == "cuda":
    spatial_model = spatial_model.to(DEVICE)

wav_proc = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base-960h")
wav_model = Wav2Vec2Model.from_pretrained(
    "facebook/wav2vec2-base-960h",
    ignore_mismatched_sizes=True
)

wav_model.eval()
if DEVICE == "cuda":
    wav_model = wav_model.to(DEVICE)
log("Models ready. Device:", DEVICE)

# ---------- Utility functions ----------
def sample_frames_from_videofile(video_path, max_frames=MAX_FRAMES):
    """Return a list of RGB frames sampled evenly up to max_frames."""
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        log("cv2 cannot open:", video_path)
        return []
    frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
    if frame_count <= 0:
        # fallback: read until exhausted but limit
        frames = []
        while len(frames) < max_frames:
            ok, f = cap.read()
            if not ok: break
            frames.append(cv2.cvtColor(f, cv2.COLOR_BGR2RGB))
        cap.release()
        return frames
    # compute evenly spaced indices
    indices = np.linspace(0, frame_count - 1, num=min(max_frames, frame_count), dtype=int)
    frames = []
    idx_set = set(indices.tolist())
    i = 0
    next_idx = 0
    current_target = indices[next_idx] if len(indices)>0 else None
    while cap.isOpened() and len(frames) < len(indices):
        ok, f = cap.read()
        if not ok:
            break
        if i == current_target:
            frames.append(cv2.cvtColor(f, cv2.COLOR_BGR2RGB))
            next_idx += 1
            if next_idx >= len(indices): break
            current_target = indices[next_idx]
        i += 1
    cap.release()
    return frames

@torch.no_grad()
def extract_spatial_faces(frames, min_face=MIN_FACE):
    """Return torch.Tensor [N, feat_dim] or None."""
    embeddings = []
    for frame in frames:
        faces = face_app.get(frame)
        if not faces:
            continue
        face = faces[0]
        if face.bbox is None:
            continue
        x1, y1, x2, y2 = map(int, face.bbox)
        if x2 <= x1 or y2 <= y1: continue
        if (x2 - x1) < min_face or (y2 - y1) < min_face: continue
        h, w, _ = frame.shape
        x1, y1 = max(0, x1), max(0, y1)
        x2, y2 = min(w, x2), min(h, y2)
        crop = frame[y1:y2, x1:x2]
        if crop.size == 0: continue
        crop = cv2.resize(crop, (224, 224))
        crop = torch.from_numpy(crop).permute(2,0,1).float() / 255.0
        crop = crop.unsqueeze(0)
        if DEVICE == "cuda":
            crop = crop.to(DEVICE)
        feat = spatial_model(crop)
        embeddings.append(feat.squeeze(0).cpu())
    if not embeddings:
        return None
    return torch.stack(embeddings)

def extract_motion(frames):
    feats = []
    prev = None
    for f in frames:
        g = cv2.cvtColor(f, cv2.COLOR_RGB2GRAY)
        if prev is None:
            feats.append(torch.zeros(256))
        else:
            diff = cv2.absdiff(prev, g)
            feats.append(torch.tensor(diff.mean()).repeat(256))
        prev = g
    return torch.stack(feats)

@torch.no_grad()
def extract_audio_with_ffmpeg(video_path, sr=AUDIO_SR, frames_count=MAX_FRAMES):
    """Extract audio features for the video using ffmpeg->wav then Wav2Vec2.
       Returns tensor [frames_count, feat_dim] on CPU.
    """
    tmp_wav = os.path.join(TMP_DIR, f"audio_{int(time.time()*1000)}.wav")
    # ffmpeg -y -i input -vn -ac 1 -ar sr -f wav tmp_wav
    cmd = ["ffmpeg", "-y", "-i", video_path, "-vn", "-ac", "1", "-ar", str(sr), "-f", "wav", tmp_wav]
    try:
        subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
    except Exception:
        # fallback: try librosa directly (less robust)
        log("ffmpeg audio extraction failed, falling back to librosa.load on:", video_path)
        try:
            y, sr2 = librosa.load(video_path, sr=sr)
            inp = wav_proc(y, return_tensors="pt", sampling_rate=sr).input_values.to(DEVICE)
            emb = wav_model(inp).last_hidden_state.mean(dim=1)
            emb = emb.cpu()
            return emb.repeat(frames_count, 1)
        except Exception as e:
            log("Audio extraction failed entirely:", e)
            return torch.zeros(frames_count, wav_model.config.hidden_size)
    try:
        y, sr2 = librosa.load(tmp_wav, sr=sr)
        os.remove(tmp_wav)
    except Exception as e:
        log("Failed to load tmp wav:", e)
        if os.path.exists(tmp_wav):
            os.remove(tmp_wav)
        return torch.zeros(frames_count, wav_model.config.hidden_size)
    # process audio to embedding
    inp = wav_proc(y, sampling_rate=sr, return_tensors="pt").input_values.to(DEVICE)
    with torch.no_grad():
        emb = wav_model(inp).last_hidden_state.mean(dim=1).cpu()
    return emb.repeat(frames_count, 1)

# 68-landmark indices (standard). Eye EAR
LEFT_EYE = [36,37,38,39,40,41]
RIGHT_EYE = [42,43,44,45,46,47]
def eye_aspect_ratio(lm, idx):
    p = lm[idx]
    vertical = np.linalg.norm(p[1] - p[5]) + np.linalg.norm(p[2] - p[4])
    horizontal = np.linalg.norm(p[0] - p[3])
    return float(vertical / (2.0 * (horizontal + 1e-6)))

def extract_rppg_signal(frames):
    means = []
    for f in frames:
        roi = f[f.shape[0]//4:3*f.shape[0]//4, f.shape[1]//4:3*f.shape[1]//4]
        r, g, b = roi[:,:,0].mean(), roi[:,:,1].mean(), roi[:,:,2].mean()
        means.append([r,g,b])
    means = np.array(means)
    means = (means - means.mean(0)) / (means.std(0) + 1e-6)
    X = means[:,0] - means[:,1]
    Y = means[:,0] + means[:,1] - 2*means[:,2]
    return X - Y

def extract_physiology(frames):
    physiology = []
    if len(frames) == 0:
        return torch.zeros(0,4)
    rppg = extract_rppg_signal(frames)
    prev = rppg[0]
    for i, f in enumerate(frames):
        faces = face_app.get(f)
        ear = 0.0
        blink = 0.0
        if faces:
            try:
                lm = faces[0].landmark_2d_68
                left = eye_aspect_ratio(lm, LEFT_EYE)
                right = eye_aspect_ratio(lm, RIGHT_EYE)
                ear = (left + right) / 2.0
                blink = 1.0 if ear < 0.2 else 0.0
            except Exception:
                ear = 0.0
                blink = 0.0
        delta = rppg[i] - prev
        prev = rppg[i]
        physiology.append([rppg[i], delta, ear, blink])
    return torch.tensor(physiology, dtype=torch.float32)

# ---------- Processing flow ----------
def process_video_file(tmp_video_path, info, zip_name, video_done, out_root=OUT_DIR):
    ensure_dir(ERRORS_DIR)

    vid = os.path.splitext(os.path.basename(tmp_video_path))[0]
    if vid in video_done and video_done[vid].get("status") == "DONE":
        return True
    label = "fake" if info.get("label") == "FAKE" else "real"
    out_dir = os.path.join(out_root, label, vid)
    ensure_dir(out_dir)

    try:
        frames = sample_frames_from_videofile(tmp_video_path, max_frames=MAX_FRAMES)
        if len(frames) < 3:
            log("Too few frames, skipping:", vid)
            return False
        features = {}
        features["spatial"] = extract_spatial_faces(frames)
        features["motion"] = extract_motion(frames)
        features["audio"] = extract_audio_with_ffmpeg(tmp_video_path, sr=AUDIO_SR, frames_count=len(frames))
        features["physiology"] = extract_physiology(frames)
        features["mask"] = torch.ones(len(frames))
        torch.save(features, os.path.join(out_dir, "features.pt"))
        meta = {"label": info.get("label"), "original": info.get("original"), "zip": zip_name}
        with open(os.path.join(out_dir, "meta.json"), "w") as f:
            json.dump(meta, f, indent=2)
        video_done[vid] = {"status":"DONE", "zip": zip_name, "ts": time.time()}
        return True
    except Exception as e:
        tb = traceback.format_exc()
        video_done[vid] = {"status":"FAILED", "zip": zip_name, "error": str(e), "ts": time.time()}
        # write detailed log
        with open(os.path.join(ERRORS_DIR, f"{zip_name}_{vid}.log"), "w") as ef:
            ef.write(tb)
        log("Video processing failed:", vid, "error:", e)
        return False

def find_dfdc_root(z):
    """
    Returns the inner DFDC folder name, e.g. 'dfdc_train_part_0'
    """
    roots = set(p.split("/")[0] for p in z.namelist() if "/" in p)
    for r in roots:
        if r.startswith("dfdc_"):
            return r
    raise RuntimeError("Could not find DFDC root folder inside zip")


def process_zip_streaming(zip_name, video_done):
    zip_path = os.path.join(ZIP_DIR, zip_name)
    log("Processing zip:", zip_path)

    with zipfile.ZipFile(zip_path, 'r') as z:
        # 1️⃣ find inner DFDC folder
        inner = find_dfdc_root(z)
        log("Found inner folder:", inner)

        # 2️⃣ load metadata.json
        meta_path = f"{inner}/metadata.json"
        with z.open(meta_path) as mf:
            metadata = json.load(mf)

        total = len(metadata)

        # 3️⃣ iterate videos
        for idx, (video_name, info) in enumerate(metadata.items(), 1):
            vid = os.path.splitext(video_name)[0]

            if vid in video_done and video_done[vid]["status"] == "DONE":
                continue

            zip_video_path = f"{inner}/{video_name}"

            tmp_dir = os.path.join(TMP_DIR, f"{vid}_{int(time.time()*1e6)}")
            os.makedirs(tmp_dir, exist_ok=True)
            tmp_video = os.path.join(tmp_dir, video_name)

            try:
                # extract single video
                with z.open(zip_video_path) as src, open(tmp_video, "wb") as dst:
                    shutil.copyfileobj(src, dst)

                ok = process_video_file(
                    tmp_video_path=tmp_video,
                    info=info,
                    zip_name=zip_name,
                    video_done=video_done
                )

                # per-video provenance file
                label = "fake" if info["label"] == "FAKE" else "real"
                out_dir = os.path.join(OUT_DIR, label, vid)

                provenance = {
                    "video": video_name,
                    "label": info["label"],
                    "original": info.get("original"),   # only for FAKE
                    "zip": zip_name,
                    "inner_folder": inner
                }

                with open(os.path.join(out_dir, "info.json"), "w") as f:
                    json.dump(provenance, f, indent=2)

                video_done[vid] = {
                    "status": "DONE",
                    "zip": zip_name
                }

                log(f"{zip_name} | {vid} DONE ({idx}/{total})")

            except Exception as e:
                tb = traceback.format_exc()
                video_done[vid] = {
                    "status": "FAILED",
                    "zip": zip_name,
                    "error": str(e)
                }

                with open(os.path.join(ERRORS_DIR, f"{zip_name}_{vid}.log"), "w") as ef:
                    ef.write(tb)

                log(f"{zip_name} | {vid} FAILED ({idx}/{total}) - {e}")

            finally:
                shutil.rmtree(tmp_dir, ignore_errors=True)
                save_video_done(video_done)

    mark_zip_done(zip_name)
    log("✅ ZIP DONE:", zip_name)


# ---------- Driver ----------
if __name__ == "__main__":
    zip_done = load_zip_done()
    video_done = load_video_done()

    zip_list = sorted([z for z in os.listdir(ZIP_DIR) if z.endswith(".zip")])
    for zip_name in zip_list:
        if zip_name in zip_done:
            continue
        try:
            process_zip_streaming(zip_name, video_done)
        except KeyboardInterrupt:
            log("Received KeyboardInterrupt. Saving progress and exiting.")
            save_video_done(video_done)
            raise
        except Exception as e:
            log("Error processing zip:", zip_name, "error:", e)
            ensure_dir(ERRORS_DIR)
            # don't crash the entire loop; mark zip as failed row
            with open(os.path.join(ERRORS_DIR, f"{zip_name}_zip_error.log"), "w") as ef:
                ef.write(traceback.format_exc())
            save_video_done(video_done)
            # continue to next zip
            continue

    log("All done (or all available zips processed).")

"""# **Method 2**"""

!pip install -q insightface==0.7.3 timm==0.9.2 transformers==4.40.0 librosa soundfile==0.12.1 onnxruntime-gpu

# DFDC T4 GPU - Robust, Efficient, Resumeable Pipeline
# =======================================================
# Drop this full cell into Colab (GPU runtime: T4). It:
# - Copies ZIP -> local NVMe to avoid Drive FUSE issues
# - Uses GPU (insightface + timm + wav2vec2) with fp16 where possible
# - Writes per-video outputs (faces.pt, spatial.pt, motion.pt, audio.pt, physiology.pt, meta.json)\# - Atomic progress CSV for parallel runs (set START_ZIP_INDEX/END_ZIP_INDEX to partition)
# - Robust retries, error logs, and idempotent outputs
#
# USAGE:
# - Ensure Colab runtime is GPU (T4). Set `START_ZIP_INDEX` / `END_ZIP_INDEX` at top to partition work.
# - Run the whole cell. Progress saved to /content/drive/MyDrive/dfdc_progress.csv
# - Output layout matches your requested structure.

# ------------------- Installs (run once) -------------------
# (Some installs can be slow; if already installed, pip will skip)

# ------------------- Imports & config ---------------------
import os, json, zipfile, shutil, time, traceback, sys
from pathlib import Path
import torch
import numpy as np
import cv2
from tqdm import tqdm
import librosa
from transformers import Wav2Vec2Processor, Wav2Vec2Model
from insightface.app import FaceAnalysis
import timm

# ------------------- USER CONFIG --------------------------
# Set these before running. Use START_ZIP_INDEX/END_ZIP_INDEX to parallelize across machines.
ZIP_DIR = "/content/drive/MyDrive/DFDC_zips"
OUT_ROOT = "/content/drive/MyDrive/DFDC_processed"
TMP_DIR = "/content/tmp_dfdc_local"   # local NVMe
PROGRESS_CSV = "/content/drive/MyDrive/dfdc_progress.csv"
VIDEO_PROGRESS_JSON = "/content/drive/MyDrive/dfdc_video_progress.json"
ERRORS_DIR = os.path.join(OUT_ROOT, "errors")

# Partitioning for parallel machines
START_ZIP_INDEX = 0   # inclusive
END_ZIP_INDEX = None  # exclusive (None means till end)

# Perf tuning
MAX_FRAMES = 32
MIN_FACE = 40
BATCH_FRAME = 8      # frames per batch for CNN (tweak for memory)
AUDIO_SR = 16000
RETRY_COPY_ATTEMPTS = 3

# Device
assert torch.cuda.is_available(), "CUDA not available - please use T4 GPU runtime"
DEVICE = "cuda"
FP16 = True  # use half precision where supported

# Ensure dirs
os.makedirs(TMP_DIR, exist_ok=True)
os.makedirs(OUT_ROOT, exist_ok=True)
os.makedirs(ERRORS_DIR, exist_ok=True)

# ------------------- Utilities ----------------------------
import csv
import subprocess
from google.colab import drive

def log(*args, **kwargs):
    ts = time.strftime('%Y-%m-%d %H:%M:%S')
    print(f"[{ts}]", *args, **kwargs)
    sys.stdout.flush()


def ensure_dir(p):
    os.makedirs(p, exist_ok=True)


def atomic_write_json(path, obj):
    tmp = path + ".tmp"
    with open(tmp, 'w') as f:
        json.dump(obj, f, indent=2)
    os.replace(tmp, path)


def load_progress_csv():
    done = set()
    if os.path.exists(PROGRESS_CSV):
        try:
            with open(PROGRESS_CSV, newline='') as f:
                for r in csv.reader(f):
                    if r: done.add(r[0])
        except Exception:
            log("Warning: couldn't read progress CSV; starting fresh")
    return done


def mark_zip_done(zip_name):
    tmp = PROGRESS_CSV + ".tmp"
    with open(tmp, 'a', newline='') as f:
        csv.writer(f).writerow([zip_name, time.time()])
    if os.path.exists(PROGRESS_CSV):
        with open(PROGRESS_CSV, 'ab') as out, open(tmp, 'rb') as inp:
            out.write(inp.read())
        os.remove(tmp)
    else:
        os.replace(tmp, PROGRESS_CSV)


def load_video_progress():
    if os.path.exists(VIDEO_PROGRESS_JSON):
        try:
            with open(VIDEO_PROGRESS_JSON) as f:
                return json.load(f)
        except Exception:
            return {}
    return {}


def save_video_progress(d):
    tmp = VIDEO_PROGRESS_JSON + ".tmp"
    with open(tmp, 'w') as f:
        json.dump(d, f)
    os.replace(tmp, VIDEO_PROGRESS_JSON)

# ------------------- Mount Drive --------------------------
# Force remount to reduce stale mount issues
try:
    drive.mount('/content/drive', force_remount=True)
except Exception:
    log('Drive mount failed; if Drive isnt needed, ensure ZIP_DIR/OUT_ROOT are local')

# ------------------- Model init ---------------------------
log('Initializing models — this may take a minute...')

# InsightFace face detector (buffalo_l) - uses ctx_id=0 for GPU if available
try:
    face_app = FaceAnalysis(name='buffalo_l')
    # If CUDA available, pass ctx_id=0; else -1
    face_app.prepare(ctx_id=0 if torch.cuda.is_available() else -1)
    log('InsightFace ready')
except Exception as e:
    log('InsightFace init failed:', e)
    raise

# Spatial model (EfficientNet B4 -> produce embeddings)
spatial_model = timm.create_model('efficientnet_b4', pretrained=True, num_classes=0)
spatial_model.eval()
if FP16:
    try:
        spatial_model = spatial_model.half()
    except Exception:
        pass
spatial_model.to(DEVICE)
log('Spatial model ready on', DEVICE)

# Wav2Vec2 audio model
wav_proc = Wav2Vec2Processor.from_pretrained('facebook/wav2vec2-base-960h')
wav_model = Wav2Vec2Model.from_pretrained('facebook/wav2vec2-base-960h')
wav_model.eval()
if FP16:
    try:
        wav_model = wav_model.half()
    except Exception:
        pass
wav_model.to(DEVICE)
log('Wav2Vec2 ready on', DEVICE)

# ------------------- Feature extractors -------------------
import numpy as np

def read_frames_even(video_path, max_frames=MAX_FRAMES):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        return []
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
    if total <= 0:
        frames = []
        while len(frames) < max_frames:
            ok, f = cap.read()
            if not ok: break
            frames.append(cv2.cvtColor(f, cv2.COLOR_BGR2RGB))
        cap.release()
        return frames
    indices = np.linspace(0, total - 1, num=min(max_frames, total), dtype=int)
    frames = []
    idx_set = set(indices.tolist())
    i = 0
    next_idx = 0
    current_target = indices[next_idx] if len(indices) > 0 else None
    while cap.isOpened() and len(frames) < len(indices):
        ok, f = cap.read()
        if not ok: break
        if i == current_target:
            frames.append(cv2.cvtColor(f, cv2.COLOR_BGR2RGB))
            next_idx += 1
            if next_idx >= len(indices): break
            current_target = indices[next_idx]
        i += 1
    cap.release()
    return frames

@torch.no_grad()
def extract_spatial_faces(frames, min_face=MIN_FACE):
    face_crops = []
    face_embeddings = []
    for frame in frames:
        faces = face_app.get(frame)
        if not faces:
            face_crops.append(None)
            continue
        f = faces[0]
        if f.bbox is None:
            face_crops.append(None)
            continue
        x1, y1, x2, y2 = map(int, f.bbox)
        if x2 <= x1 or y2 <= y1:
            face_crops.append(None); continue
        if (x2-x1) < min_face or (y2-y1) < min_face:
            face_crops.append(None); continue
        h, w, _ = frame.shape
        x1, y1 = max(0,x1), max(0,y1)
        x2, y2 = min(w,x2), min(h,y2)
        crop = frame[y1:y2, x1:x2]
        if crop.size == 0:
            face_crops.append(None); continue
        face_crops.append(crop)
        # preprocess for spatial_model
        img = cv2.resize(crop, (224,224))
        img = torch.from_numpy(img).permute(2,0,1).float()/255.0
        if FP16:
            img = img.half()
        img = img.unsqueeze(0).to(DEVICE)
        feat = spatial_model(img)
        face_embeddings.append(feat.squeeze(0).cpu())
    if face_embeddings:
        spatial = torch.stack(face_embeddings)
    else:
        spatial = None
    return face_crops, spatial


def extract_motion(frames):
    feats = []
    prev = None
    for f in frames:
        g = cv2.cvtColor(f, cv2.COLOR_RGB2GRAY)
        if prev is None:
            feats.append(torch.zeros(256))
        else:
            diff = cv2.absdiff(prev, g)
            feats.append(torch.tensor(diff.mean()).repeat(256))
        prev = g
    return torch.stack(feats)

@torch.no_grad()
def extract_audio(video_path, frames_len, sr=AUDIO_SR):
    # use ffmpeg via subprocess to extract wav robustly
    tmp_wav = os.path.join(TMP_DIR, f"audio_{int(time.time()*1000)}.wav")
    cmd = ['ffmpeg', '-y', '-i', video_path, '-vn', '-ac', '1', '-ar', str(sr), '-f', 'wav', tmp_wav]
    try:
        subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
        y, _ = librosa.load(tmp_wav, sr=sr)
        os.remove(tmp_wav)
    except Exception:
        # fallback to librosa directly (less robust)
        try:
            y, _ = librosa.load(video_path, sr=sr)
        except Exception:
            return torch.zeros(frames_len, wav_model.config.hidden_size)
    inp = wav_proc(y, sampling_rate=sr, return_tensors='pt', padding=True).input_values.to(DEVICE)
    if FP16:
        try: inp = inp.half()
        except Exception: pass
    emb = wav_model(inp).last_hidden_state.mean(dim=1).cpu()
    return emb.repeat(frames_len, 1)

# physiology helpers
LEFT_EYE = [36,37,38,39,40,41]
RIGHT_EYE = [42,43,44,45,46,47]

def eye_aspect_ratio(lm, idx):
    p = lm[idx]
    vertical = np.linalg.norm(p[1]-p[5]) + np.linalg.norm(p[2]-p[4])
    horizontal = np.linalg.norm(p[0]-p[3])
    return float(vertical/(2.0*(horizontal+1e-6)))


def extract_rppg_signal(frames):
    means = []
    for f in frames:
        roi = f[f.shape[0]//4:3*f.shape[0]//4, f.shape[1]//4:3*f.shape[1]//4]
        r,g,b = roi[:,:,0].mean(), roi[:,:,1].mean(), roi[:,:,2].mean()
        means.append([r,g,b])
    means = np.array(means)
    means = (means - means.mean(0)) / (means.std(0) + 1e-6)
    X = means[:,0] - means[:,1]
    Y = means[:,0] + means[:,1] - 2*means[:,2]
    return X - Y


def extract_physiology(frames):
    if len(frames) == 0:
        return torch.zeros(0,4)
    rppg = extract_rppg_signal(frames)
    prev = rppg[0]
    physiology = []
    for i, f in enumerate(frames):
        faces = face_app.get(f)
        ear = 0.0; blink = 0.0
        if faces:
            try:
                lm = faces[0].landmark_2d_68
                left = eye_aspect_ratio(lm, LEFT_EYE)
                right = eye_aspect_ratio(lm, RIGHT_EYE)
                ear = (left + right)/2.0
                blink = 1.0 if ear < 0.2 else 0.0
            except Exception:
                ear = 0.0; blink = 0.0
        delta = rppg[i] - prev
        prev = rppg[i]
        physiology.append([rppg[i], float(delta), ear, blink])
    return torch.tensor(physiology, dtype=torch.float32)

# ------------------- Zip helpers (robust copy) --------------

def copy_zip_to_local(src_zip, dst_zip, attempts=RETRY_COPY_ATTEMPTS):
    # streaming copy with retries
    for attempt in range(1, attempts+1):
        try:
            with open(src_zip, 'rb') as sf, open(dst_zip, 'wb') as df:
                shutil.copyfileobj(sf, df, length=1024*1024)
            if os.path.exists(dst_zip) and os.path.getsize(dst_zip) > 0:
                return True
        except OSError as e:
            log(f'copy attempt {attempt} failed: {e}')
            # remount drive if transport endpoint error
            if getattr(e, 'errno', None) == 107:
                try:
                    drive.mount('/content/drive', force_remount=True)
                    log('Drive remounted after transport error')
                except Exception:
                    pass
            time.sleep(2 ** attempt)
        except Exception as e:
            log('copy exception', e)
            time.sleep(1)
    return False


def find_inner_root_in_zip(z):
    # find the path that contains metadata.json
    for n in z.namelist():
        if n.endswith('metadata.json'):
            return os.path.dirname(n)
    raise RuntimeError('metadata.json not found in zip')

# ------------------- Main processing -----------------------

log('Scanning zip directory...')
zip_names = sorted([z for z in os.listdir(ZIP_DIR) if z.endswith('.zip')])
if END_ZIP_INDEX is None:
    zip_names = zip_names[START_ZIP_INDEX:]
else:
    zip_names = zip_names[START_ZIP_INDEX:END_ZIP_INDEX]
log('Assigned', len(zip_names), 'zips to this worker')

video_progress = load_video_progress()

for zip_name in zip_names:
    try:
        if zip_name in load_progress_csv():
            log(zip_name, 'already marked done - skipping')
            continue
        src_zip = os.path.join(ZIP_DIR, zip_name)
        local_zip = os.path.join(TMP_DIR, zip_name)
        log('Copying zip to local NVMe:', zip_name)
        ok = copy_zip_to_local(src_zip, local_zip, attempts=RETRY_COPY_ATTEMPTS)
        if not ok:
            log('Failed to copy zip, skipping:', zip_name)
            continue

        with zipfile.ZipFile(local_zip, 'r') as z:
            inner = find_inner_root_in_zip(z)
            log('Found inner folder:', inner)
            with z.open(f"{inner}/metadata.json") as mf:
                meta = json.load(mf)

            total = len(meta)
            for idx, (vname, info) in enumerate(meta.items(), start=1):
                vid = os.path.splitext(vname)[0]
                label = 'fake' if info['label'] == 'FAKE' else 'real'
                out_dir = os.path.join(OUT_ROOT, label, vid)
                ensure_dir(out_dir)

                # idempotent check
                if os.path.exists(os.path.join(out_dir, 'meta.json')):
                    video_progress[vid] = {'status': 'DONE', 'zip': zip_name}
                    if idx % 50 == 0:
                        log(f'{zip_name}: already processed {idx}/{total}')
                    continue

                tmp_vfile = os.path.join(TMP_DIR, f"{vid}.mp4")
                try:
                    # extract single video to local temp
                    with z.open(f"{inner}/{vname}") as vf, open(tmp_vfile, 'wb') as outv:
                        shutil.copyfileobj(vf, outv)

                    frames = read_frames_even(tmp_vfile, max_frames=MAX_FRAMES)
                    if len(frames) < 3:
                        raise RuntimeError('Too few frames')

                    # faces + spatial
                    face_crops, spatial_emb = extract_spatial_faces(frames)
                    # motion
                    motion = extract_motion(frames)
                    # physiology
                    physiology = extract_physiology(frames)
                    # audio
                    audio_emb = extract_audio(tmp_vfile, frames_len=len(frames), sr=AUDIO_SR)

                    # save pieces atomically
                    torch.save(face_crops, os.path.join(out_dir, 'faces.pt'))
                    if spatial_emb is not None:
                        torch.save(spatial_emb, os.path.join(out_dir, 'spatial.pt'))
                    else:
                        # save empty tensor to maintain schema
                        torch.save(torch.zeros(0), os.path.join(out_dir, 'spatial.pt'))
                    torch.save(motion, os.path.join(out_dir, 'motion.pt'))
                    torch.save(audio_emb, os.path.join(out_dir, 'audio.pt'))
                    torch.save(physiology, os.path.join(out_dir, 'physiology.pt'))

                    meta_out = {
                        'label': info.get('label'),
                        'original': info.get('original'),
                        'zip': zip_name,
                        'inner_folder': inner
                    }
                    atomic_write_json(os.path.join(out_dir, 'meta.json'), meta_out)

                    video_progress[vid] = {'status': 'DONE', 'zip': zip_name}
                    save_video_progress(video_progress)

                    if idx % 50 == 0:
                        log(f"{zip_name}: processed {idx}/{total} videos — flushing progress")
                    else:
                        log(f"{zip_name} | {vid} DONE ({idx}/{total})")

                except Exception as e:
                    tb = traceback.format_exc()
                    video_progress[vid] = {'status': 'FAILED', 'zip': zip_name, 'error': str(e)}
                    save_video_progress(video_progress)
                    ensure_dir(ERRORS_DIR)
                    with open(os.path.join(ERRORS_DIR, f"{zip_name}_{vid}.log"), 'w') as ef:
                        ef.write(tb)
                    log(f"{zip_name} | {vid} FAILED ({idx}/{total}) - {e}")

                finally:
                    try:
                        if os.path.exists(tmp_vfile):
                            os.remove(tmp_vfile)
                    except Exception:
                        pass

        # zip finished!
        mark_zip_done(zip_name)
        log('✅ ZIP DONE:', zip_name)

    except Exception as e:
        tb = traceback.format_exc()
        ensure_dir(ERRORS_DIR)
        with open(os.path.join(ERRORS_DIR, f"{zip_name}_zip_error.log"), 'w') as ef:
            ef.write(tb)
        log('Error processing zip:', zip_name, 'error:', e)
    finally:
        # always try to remove local copy to free disk
        try:
            if os.path.exists(local_zip):
                os.remove(local_zip)
        except Exception:
            pass

log('ALL ASSIGNED ZIPS COMPLETE')

# ------------------- Output structure ---------------------
# The script writes exactly this structure under /content/drive/MyDrive/DFDC_processed/
# real/<vid>/{faces.pt, spatial.pt, motion.pt, audio.pt, physiology.pt, meta.json}
# fake/<vid>/{...}
# and a top-level dfdc_progress.csv which tracks finished zips

# ------------------- Notes --------------------------------
# - If ffmpeg isn't present, install it via apt-get. Colab typically has ffmpeg preinstalled.
# - If you want to run multiple machines, set START_ZIP_INDEX and END_ZIP_INDEX on each machine
#   so they process disjoint ranges of zip files.
# - The code uses fp16 where safe; if you see numerical issues, set FP16 = False at top.
# - The pipeline aims to be robust, but cloud filesystems can still fail; progress is checkpointed.
# - You can tune MAX_FRAMES, BATCH_FRAME, and RETRY_COPY_ATTEMPTS for performance.