# -*- coding: utf-8 -*-
"""Yuktha_DFDC_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ktSrX-gLfI3_hFHXq3A1NlGSZLnFw-l
"""

from google.colab import drive
drive.mount('/content/drive')

# -------------------- Installs (run once) --------------------
!pip install -q torchmetrics scikit-learn timm

import os
import shutil
from concurrent.futures import ThreadPoolExecutor
from tqdm.auto import tqdm
import time

# --- CONFIG ---
SOURCE_DIR = "/content/drive/MyDrive/DFDC_processed"
DEST_DIR = "/content/DFDC_Local"
NUM_THREADS = 16  # 16 parallel threads is the sweet spot for Colab Drive

def copy_file(src_dst):
    src, dst = src_dst
    try:
        if os.path.exists(dst): return # Skip existing
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(src, dst)
    except Exception as e:
        print(f"Error copying {src}: {e}")

def fast_copy():
    # 1. Index all files first (Fast)
    print(f"📂 Indexing files in {SOURCE_DIR}...")
    files_to_copy = []

    for root, dirs, files in os.walk(SOURCE_DIR):
        for file in files:
            src_path = os.path.join(root, file)
            # Create corresponding local path
            rel_path = os.path.relpath(src_path, SOURCE_DIR)
            dst_path = os.path.join(DEST_DIR, rel_path)
            files_to_copy.append((src_path, dst_path))

    print(f"✅ Found {len(files_to_copy):,} files. Starting Multi-Threaded Copy...")

    # 2. Parallel Copy (The Speedup)
    start_t = time.time()
    with ThreadPoolExecutor(max_workers=NUM_THREADS) as executor:
        list(tqdm(executor.map(copy_file, files_to_copy), total=len(files_to_copy), unit="file"))

    duration = (time.time() - start_t) / 60
    print(f"🚀 Done! Copied {len(files_to_copy)} files in {duration:.1f} minutes.")

# Run it
fast_copy()

# Full DFDC training & evaluation (Colab T4-ready)
# - Per-stream models: Face, Motion, Audio, Physiology
# - Late fusion model
# - AMP, GPU (T4), checkpointing, robust loading
# - Debug prints at every stage
# ==========================================================


# ---------------- imports ---------------------------------
import os, json, time, random, math, traceback
from pathlib import Path
from typing import List, Tuple, Dict, Optional
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from torch.optim import AdamW
import torch.backends.cudnn as cudnn
import gc

# ---------------- user config -----------------------------
OUT_ROOT = "/content/drive/MyDrive/DFDC_processed"   # processed features root
CKPT_DIR = "/content/drive/MyDrive/dfdc_train_ckpts"
os.makedirs(CKPT_DIR, exist_ok=True)

# training hyperparams
SEED = 42
BATCH_SIZE = 64             # tune for T4 memory. 64 or 32 typically works
NUM_WORKERS = 2
EPOCHS_STREAM = 6
EPOCHS_FUSION = 6
LR = 1e-4
WEIGHT_DECAY = 1e-5
USE_AMP = True

# device
assert torch.cuda.is_available(), "Please run on a GPU runtime (T4)"
DEVICE = torch.device("cuda")
print("Using device:", torch.cuda.get_device_name(0))
cudnn.benchmark = True

# reproducibility
def set_seed(s=SEED):
    random.seed(s); np.random.seed(s); torch.manual_seed(s); torch.cuda.manual_seed_all(s)
set_seed()

# ---------------- utility logging ------------------------
def log(*args, **kwargs):
    ts = time.strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}]", *args, **kwargs)
    # flush for colab real-time visibility
    try:
        import sys; sys.stdout.flush()
    except:
        pass

# ---------------- Dataset -------------------------------
class DFDCProcessedDataset(Dataset):
    """
    Loads saved feature files for each video.
    FORCE CASTS everything to float32 to prevent Double vs Half errors.
    """
    def __init__(self, root: str, ids: Optional[List[str]] = None):
        self.root = Path(root)
        self.items = []
        for label in ["real", "fake"]:
            p = self.root / label
            if not p.exists():
                continue
            for vid_dir in p.iterdir():
                if not vid_dir.is_dir(): continue
                vid_name = vid_dir.name
                if ids is not None and vid_name not in ids:
                    continue
                meta = vid_dir / "meta.json"
                if not meta.exists(): continue
                with open(meta) as f:
                    m = json.load(f)
                lab = 0 if m.get("label","REAL").upper()=="REAL" else 1
                self.items.append((str(vid_dir), lab))
        self.items = sorted(self.items)
        log("Dataset built with", len(self.items), "videos")

    def __len__(self):
        return len(self.items)

    def _safe_load(self, path: Path):
        try:
            if not path.exists():
                return None
            # Load and immediately ensure it is a float32 tensor
            data = torch.load(str(path))
            if isinstance(data, np.ndarray):
                data = torch.from_numpy(data)
            return data.float() # <--- CRITICAL FIX: Force float32
        except Exception as e:
            return None

    def summarize_temporal(self, x):
        # x: Tensor [T, D] or None
        if x is None:
            return None

        # Ensure x is float32 before processing
        x = x.float()

        if len(x.shape) == 1:
            mean = x
            std = torch.zeros_like(mean)
            return torch.cat([mean, std], dim=0)

        mean = x.mean(dim=0)
        std = x.std(dim=0)
        return torch.cat([mean, std], dim=0)

    def __getitem__(self, idx):
        path, label = self.items[idx]
        p = Path(path)

        # _safe_load now guarantees float32 or None
        spatial = self._safe_load(p / "spatial.pt")
        motion = self._safe_load(p / "motion.pt")
        audio = self._safe_load(p / "audio.pt")
        phys = self._safe_load(p / "physiology.pt")

        # Spatial handling
        if isinstance(spatial, torch.Tensor) and spatial.numel() > 0:
            spatial_mean = spatial.mean(dim=0)
        else:
            spatial_mean = torch.zeros(512).float() # <--- Ensure float32

        motion_sum = self.summarize_temporal(motion)
        if motion_sum is None:
            motion_sum = torch.zeros(256*2).float() # <--- Ensure float32

        audio_sum = self.summarize_temporal(audio)
        if audio_sum is None:
            audio_sum = torch.zeros(512*2).float() # <--- Ensure float32

        phys_sum = self.summarize_temporal(phys)
        if phys_sum is None:
            phys_sum = torch.zeros(4*2).float() # <--- Ensure float32

        return {
            "spatial": spatial_mean,
            "motion": motion_sum,
            "audio": audio_sum,
            "phys": phys_sum,
            "label": torch.tensor(label, dtype=torch.float32),
            "id": Path(path).name
        }

def collate_fn(batch):
    spatial = torch.stack([b["spatial"] for b in batch])
    motion = torch.stack([b["motion"] for b in batch])
    audio = torch.stack([b["audio"] for b in batch])
    phys = torch.stack([b["phys"] for b in batch])
    labels = torch.stack([b["label"] for b in batch])
    ids = [b["id"] for b in batch]
    return {"spatial": spatial, "motion": motion, "audio": audio, "phys": phys, "label": labels, "ids": ids}

# ---------------- prepare dataset & loaders -----------------
all_ds = DFDCProcessedDataset(OUT_ROOT)
n = len(all_ds)
if n == 0:
    raise SystemExit("No processed videos found under " + OUT_ROOT)

# build ids & labels for stratified split
ids = [Path(p).name for p,_ in all_ds.items]
labels = [lab for _,lab in all_ds.items]
train_idx, val_idx = train_test_split(list(range(n)), test_size=0.15, stratify=labels, random_state=SEED)
train_ids = [ids[i] for i in train_idx]
val_ids = [ids[i] for i in val_idx]
log(f"Total videos: {n}  Train: {len(train_ids)}  Val: {len(val_ids)}")

train_ds = DFDCProcessedDataset(OUT_ROOT, ids=train_ids)
val_ds = DFDCProcessedDataset(OUT_ROOT, ids=val_ids)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=NUM_WORKERS, collate_fn=collate_fn, pin_memory=True)
val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS, collate_fn=collate_fn, pin_memory=True)

# peek batch to infer dims
batch0 = next(iter(train_loader))
spatial_dim = batch0["spatial"].shape[1]
motion_dim = batch0["motion"].shape[1]
audio_dim = batch0["audio"].shape[1]
phys_dim = batch0["phys"].shape[1]
log("Feature dims inferred:", "spatial", spatial_dim, "motion", motion_dim, "audio", audio_dim, "phys", phys_dim)

# ---------------- model definitions ------------------------
# Lightweight but powerful encoders (fast on T4)
def make_mlp(in_dim, hidden=512, embed_dim=128, dropout=0.3):
    return nn.Sequential(
        nn.Linear(in_dim, hidden),
        nn.BatchNorm1d(hidden),
        nn.ReLU(inplace=True),
        nn.Dropout(dropout),
        nn.Linear(hidden, embed_dim),
        nn.ReLU(inplace=True)
    )

class FaceEncoder(nn.Module):
    def __init__(self, in_dim, embed_dim=128):
        super().__init__()
        self.enc = make_mlp(in_dim, hidden=512, embed_dim=embed_dim)
        self.classifier = nn.Linear(embed_dim, 1)
    def forward(self, x):
        emb = self.enc(x)
        logit = self.classifier(emb).squeeze(1)
        return logit, emb

class MotionEncoder(nn.Module):
    def __init__(self, in_dim, embed_dim=128):
        super().__init__()
        # in_dim = Dm*2 (mean+std)
        self.enc = make_mlp(in_dim, hidden=512, embed_dim=embed_dim)
        self.classifier = nn.Linear(embed_dim, 1)
    def forward(self, x):
        emb = self.enc(x)
        logit = self.classifier(emb).squeeze(1)
        return logit, emb

class AudioEncoder(nn.Module):
    def __init__(self, in_dim, embed_dim=128, hidden=256):
        super().__init__()
        # We'll use a small BiLSTM over the summarized vector interpreted as sequence of half-length
        # But since we have mean+std summary, we'll treat it as vector and pass through MLP
        self.enc = make_mlp(in_dim, hidden=512, embed_dim=embed_dim)
        self.classifier = nn.Linear(embed_dim, 1)
    def forward(self, x):
        emb = self.enc(x)
        logit = self.classifier(emb).squeeze(1)
        return logit, emb

class PhysEncoder(nn.Module):
    def __init__(self, in_dim, embed_dim=64):
        super().__init__()
        self.enc = make_mlp(in_dim, hidden=256, embed_dim=embed_dim)
        self.classifier = nn.Linear(embed_dim, 1)
    def forward(self, x):
        emb = self.enc(x)
        logit = self.classifier(emb).squeeze(1)
        return logit, emb

class FusionHead(nn.Module):
    def __init__(self, emb_dims: Dict[str,int]):
        super().__init__()
        tot = sum(emb_dims.values())
        self.net = nn.Sequential(
            nn.Linear(tot, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(512, 128),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(128, 1)
        )
    def forward(self, emb_cat):
        return self.net(emb_cat).squeeze(1)

# ---------------- instantiate models -----------------------
face_enc = FaceEncoder(spatial_dim, embed_dim=128).to(DEVICE)
motion_enc = MotionEncoder(motion_dim, embed_dim=128).to(DEVICE)
audio_enc = AudioEncoder(audio_dim, embed_dim=128).to(DEVICE)
phys_enc = PhysEncoder(phys_dim, embed_dim=64).to(DEVICE)

log("Models moved to device. Parameter counts:",
    "face", sum(p.numel() for p in face_enc.parameters()),
    "motion", sum(p.numel() for p in motion_enc.parameters()),
    "audio", sum(p.numel() for p in audio_enc.parameters()),
    "phys", sum(p.numel() for p in phys_enc.parameters()))

# ---------------- training utilities -----------------------
scaler = torch.cuda.amp.GradScaler(enabled=USE_AMP)

def train_epoch_encoder(model, loader, optimizer, epoch, name):
    model.train()
    losses = []
    all_logits = []
    all_labels = []
    tic = time.time()
    for i, batch in enumerate(loader, 1):
        spatial = batch["spatial"].to(DEVICE)
        motion = batch["motion"].to(DEVICE)
        audio = batch["audio"].to(DEVICE)
        phys = batch["phys"].to(DEVICE)
        labels = batch["label"].to(DEVICE)
        optimizer.zero_grad()
        with torch.cuda.amp.autocast(enabled=USE_AMP):
            if name == "face":
                logits, _ = model(spatial)
            elif name == "motion":
                logits, _ = model(motion)
            elif name == "audio":
                logits, _ = model(audio)
            elif name == "phys":
                logits, _ = model(phys)
            else:
                raise ValueError(name)
            loss = F.binary_cross_entropy_with_logits(logits, labels)
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        losses.append(loss.item())
        all_logits.append(logits.detach().cpu().numpy())
        all_labels.append(labels.detach().cpu().numpy())
        if i % 50 == 0:
            log(f"{name} Epoch {epoch} step {i}/{len(loader)} loss {np.mean(losses):.4f}")
    toc = time.time()
    logits = np.concatenate(all_logits) if all_logits else np.array([])
    labels = np.concatenate(all_labels) if all_labels else np.array([])
    auc = roc_auc_score(labels, logits) if len(labels)>0 and len(np.unique(labels))>1 else float('nan')
    log(f"{name} Epoch {epoch} finished in {toc-tic:.1f}s loss {np.mean(losses):.4f} train_auc {auc:.4f}")
    return np.mean(losses), auc

@torch.no_grad()
def eval_encoder(model, loader, name):
    model.eval()
    all_logits = []
    all_labels = []
    for batch in loader:
        spatial = batch["spatial"].to(DEVICE)
        motion = batch["motion"].to(DEVICE)
        audio = batch["audio"].to(DEVICE)
        phys = batch["phys"].to(DEVICE)
        labels = batch["label"].to(DEVICE)
        with torch.cuda.amp.autocast(enabled=USE_AMP):
            if name == "face":
                logits, _ = model(spatial)
            elif name == "motion":
                logits, _ = model(motion)
            elif name == "audio":
                logits, _ = model(audio)
            elif name == "phys":
                logits, _ = model(phys)
            else:
                raise ValueError(name)
        all_logits.append(logits.detach().cpu().numpy())
        all_labels.append(labels.detach().cpu().numpy())
    logits = np.concatenate(all_logits) if all_logits else np.array([])
    labels = np.concatenate(all_labels) if all_labels else np.array([])
    auc = roc_auc_score(labels, logits) if len(labels)>0 and len(np.unique(labels))>1 else float('nan')
    log(f"Eval {name}: AUC {auc:.4f}")
    return auc

# ---------------- train each stream ------------------------
log("Starting per-stream training...")
stream_results = {}

# small helper to train & save best
def train_and_save(stream_name, model, epochs=EPOCHS_STREAM):
    optimizer = AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
    best_auc = 0.0
    best_path = os.path.join(CKPT_DIR, f"{stream_name}_best.pth")
    for ep in range(1, epochs+1):
        train_epoch_encoder(model, train_loader, optimizer, ep, stream_name)
        auc = eval_encoder(model, val_loader, stream_name)
        if not math.isnan(auc) and auc > best_auc:
            best_auc = auc
            torch.save(model.state_dict(), best_path)
            log(f"{stream_name} checkpoint saved to {best_path}")
    stream_results[stream_name] = best_auc
    log(f"{stream_name} best val AUC = {best_auc:.4f}")
    return best_auc

# Train face
log("Training Face encoder (spatial embeddings -> MLP)...")
face_best = train_and_save("face", face_enc)
# Train motion
log("Training Motion encoder ...")
motion_best = train_and_save("motion", motion_enc)
# Train audio
log("Training Audio encoder ...")
audio_best = train_and_save("audio", audio_enc)
# Train phys
log("Training Phys encoder ...")
phys_best = train_and_save("phys", phys_enc)

log("Per-stream training complete. Results so far:", stream_results)

# ---------------- build fusion model -----------------------
# Load best weights
def load_if_exists(model, name):
    path = os.path.join(CKPT_DIR, f"{name}_best.pth")
    if os.path.exists(path):
        try:
            model.load_state_dict(torch.load(path, map_location=DEVICE))
            log(f"Loaded {name} weights from {path}")
        except Exception as e:
            log(f"Failed loading {name} weights: {e}")

load_if_exists(face_enc, "face")
load_if_exists(motion_enc, "motion")
load_if_exists(audio_enc, "audio")
load_if_exists(phys_enc, "phys")

# Freeze encoders for fusion training
for p in face_enc.parameters(): p.requires_grad = False
for p in motion_enc.parameters(): p.requires_grad = False
for p in audio_enc.parameters(): p.requires_grad = False
for p in phys_enc.parameters(): p.requires_grad = False

emb_dims = {"face":128, "motion":128, "audio":128, "phys":64}
fusion = FusionHead(emb_dims).to(DEVICE)
log("Fusion model created. Training fusion head only.")

# ---------------- fusion dataloader wrapper ----------------
class FusionDatasetWrapper(Dataset):
    def __init__(self, base_dataset):
        self.base = base_dataset
    def __len__(self):
        return len(self.base)
    def __getitem__(self, idx):
        item = self.base[idx]
        return item

fusion_train_loader = DataLoader(FusionDatasetWrapper(train_ds), batch_size=BATCH_SIZE, shuffle=True, num_workers=NUM_WORKERS, collate_fn=collate_fn, pin_memory=True)
fusion_val_loader = DataLoader(FusionDatasetWrapper(val_ds), batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS, collate_fn=collate_fn, pin_memory=True)

# forward helper to get concatenated embeddings
@torch.no_grad()
def get_embeddings_batch(batch):
    spatial = batch["spatial"].to(DEVICE)
    motion = batch["motion"].to(DEVICE)
    audio = batch["audio"].to(DEVICE)
    phys = batch["phys"].to(DEVICE)
    # encoders return (logit, emb)
    _, f_emb = face_enc(spatial)
    _, m_emb = motion_enc(motion)
    _, a_emb = audio_enc(audio)
    _, p_emb = phys_enc(phys)
    return torch.cat([f_emb, m_emb, a_emb, p_emb], dim=1), batch["label"].to(DEVICE)

# training fusion
opt_fusion = AdamW(fusion.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
scaler_f = torch.cuda.amp.GradScaler(enabled=USE_AMP)
best_fusion_auc = 0.0
for epoch in range(1, EPOCHS_FUSION+1):
    fusion.train()
    losses = []
    start = time.time()
    for i, batch in enumerate(fusion_train_loader, 1):
        emb_cat, labels = get_embeddings_batch(batch)
        opt_fusion.zero_grad()
        with torch.cuda.amp.autocast(enabled=USE_AMP):
            logits = fusion(emb_cat)
            loss = F.binary_cross_entropy_with_logits(logits, labels)
        scaler_f.scale(loss).backward()
        scaler_f.step(opt_fusion)
        scaler_f.update()
        losses.append(loss.item())
        if i % 50 == 0:
            log(f"Fusion Epoch {epoch} step {i}/{len(fusion_train_loader)} loss {np.mean(losses):.4f}")
    dur = time.time() - start
    # eval
    fusion.eval()
    all_logits = []
    all_labels = []
    with torch.no_grad():
        for batch in fusion_val_loader:
            emb_cat, labels = get_embeddings_batch(batch)
            out = fusion(emb_cat)
            all_logits.append(out.detach().cpu().numpy())
            all_labels.append(labels.detach().cpu().numpy())
    all_logits = np.concatenate(all_logits) if all_logits else np.array([])
    all_labels = np.concatenate(all_labels) if all_labels else np.array([])
    val_auc = roc_auc_score(all_labels, all_logits) if len(all_labels)>0 and len(np.unique(all_labels))>1 else float('nan')
    log(f"Fusion Epoch {epoch} done in {dur:.1f}s  val_auc {val_auc:.4f}")
    if not math.isnan(val_auc) and val_auc > best_fusion_auc:
        best_fusion_auc = val_auc
        torch.save(fusion.state_dict(), os.path.join(CKPT_DIR, "fusion_best.pth"))
        log("Saved fusion_best.pth")

# ---------------- final evaluations & summary ----------------
final_results = {
    "Face only": stream_results.get("face", float('nan')),
    "Motion only": stream_results.get("motion", float('nan')),
    "Audio only": stream_results.get("audio", float('nan')),
    "Physiology only": stream_results.get("phys", float('nan')),
    "Fusion (all)": best_fusion_auc
}
log("FINAL RESULTS (AUC):")
for k,v in final_results.items():
    print(f"{k}\t{v:.4f}")

# save summary
with open(os.path.join(CKPT_DIR, "results_summary.json"), "w") as f:
    json.dump(final_results, f, indent=2)

log("Training complete. Checkpoints and results saved to:", CKPT_DIR)